name: todo_app
description: Todo App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # uuid
  uuid: ^3.0.6

  # format datetime
  intl: ^0.17.0
  date_format: ^2.0.6

  # database storage
  sqflite: ^2.0.0+3
  hive_generator: ^1.1.3
  hive: ^2.2.3
  build_runner: ^2.1.11
  hive_flutter: ^1.1.0

  # navigation
  salomon_bottom_bar: ^3.3.1
  page_transition: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true